// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCtJQPHNswhnxVMBmn_JDawhUlmtxHeZM',
    appId: '1:295678864449:web:963e2fe5972df503a02ac0',
    messagingSenderId: '295678864449',
    projectId: 'swift-chat-72c78',
    authDomain: 'swift-chat-72c78.firebaseapp.com',
    storageBucket: 'swift-chat-72c78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0F3Xn770E7LixO7O5dHHiKO-Z6rl2w7w',
    appId: '1:295678864449:android:ea4c840f047a95f5a02ac0',
    messagingSenderId: '295678864449',
    projectId: 'swift-chat-72c78',
    storageBucket: 'swift-chat-72c78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgnZvBgiADgVj_xIe_uHV-lrzpg4FAZuA',
    appId: '1:295678864449:ios:04d1157164f0bc40a02ac0',
    messagingSenderId: '295678864449',
    projectId: 'swift-chat-72c78',
    storageBucket: 'swift-chat-72c78.appspot.com',
    iosClientId: '295678864449-lqs72uea7sr212va7meii8ojsc2qv6ak.apps.googleusercontent.com',
    iosBundleId: 'com.ronbarzilay.swiftChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgnZvBgiADgVj_xIe_uHV-lrzpg4FAZuA',
    appId: '1:295678864449:ios:450dda63af68c6aea02ac0',
    messagingSenderId: '295678864449',
    projectId: 'swift-chat-72c78',
    storageBucket: 'swift-chat-72c78.appspot.com',
    iosClientId: '295678864449-njttbq5gcf6j522hesppt6psdcnielab.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftChat',
  );
}
